title: ol-rotate-feature
description: Rotate vector features interaction for OpenLayers

theme: jekyll-theme-cayman

plugins:
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:
    id: UA-98870917-1
    anonymizeIp: false
